Season.create!(seasonNumber: 1, name: "Season One")
Season.create!(seasonNumber: 2, name: "Season Two")
Season.create!(seasonNumber: 3, name: "Season Three")
Season.create!(seasonNumber: 4, name: "Season Four")
Season.create!(seasonNumber: 5, name: "Season Five")
Season.create!(seasonNumber: 6, name: "Season Six")

Episode.create!( episodeNumber: 1,name: "Winter is Coming",wikia: "http://gameofthrones.wikia.com/wiki/Winter_is_Coming", imdb: "http://www.imdb.com/title/tt1480055/", wiki: "https://en.wikipedia.org/wiki/Winter_Is_Coming", season_id: 1 )
Episode.create!( episodeNumber: 2,name: "The Kingsroad",wikia: "http://gameofthrones.wikia.com/wiki/The_Kingsroad", imdb: "http://www.imdb.com/title/tt1668746/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_Kingsroad", season_id: 1 )
Episode.create!( episodeNumber: 3,name: "Lord Snow",wikia: "http://gameofthrones.wikia.com/wiki/Lord_Snow", imdb: "http://www.imdb.com/title/tt1829962/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Lord_Snow", season_id: 1 )
Episode.create!( episodeNumber: 4,name: "Cripples, Bastards and Broken Things",wikia: "http://gameofthrones.wikia.com/wiki/Cripples,_Bastards_and_Broken_Things", imdb: "http://www.imdb.com/title/tt1829963/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Cripples,_Bastards,_and_Broken_Things", season_id: 1 )
Episode.create!( episodeNumber: 5,name: "The Wolf and the Lion",wikia: "http://gameofthrones.wikia.com/wiki/The_Wolf_and_the_Lion", imdb: "http://www.imdb.com/title/tt1829964/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_Wolf_and_the_Lion", season_id: 1 )
Episode.create!( episodeNumber: 6,name: "A Golden Crown",wikia: "http://gameofthrones.wikia.com/wiki/A_Golden_Crown", imdb: "http://www.imdb.com/title/tt1837862/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/A_Golden_Crown", season_id: 1 )
Episode.create!( episodeNumber: 7,name: "You Win or You Die",wikia: "http://gameofthrones.wikia.com/wiki/You_Win_or_You_Die", imdb: "http://www.imdb.com/title/tt1837863/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/You_Win_or_You_Die", season_id: 1 )
Episode.create!( episodeNumber: 8,name: "The Pointy End",wikia: "http://gameofthrones.wikia.com/wiki/The_Pointy_End", imdb: "http://www.imdb.com/title/tt1837864/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_Pointy_End", season_id: 1 )
Episode.create!( episodeNumber: 9,name: "Baelor",wikia: "http://gameofthrones.wikia.com/wiki/Baelor", imdb: "http://www.imdb.com/title/tt1851398/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Baelor", season_id: 1 )
Episode.create!( episodeNumber: 10,name: "Fire and Blood",wikia: "http://gameofthrones.wikia.com/wiki/Fire_and_Blood", imdb: "http://www.imdb.com/title/tt1851397/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Fire_and_Blood_(Game_of_Thrones)", season_id: 1 )
Episode.create!( episodeNumber: 1,name: "The North Remembers",wikia: "http://gameofthrones.wikia.com/wiki/The_North_Remembers", imdb: "http://www.imdb.com/title/tt1971833/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_North_Remembers", season_id: 2 )
Episode.create!( episodeNumber: 2,name: "The Night Lands",wikia: "http://gameofthrones.wikia.com/wiki/The_Night_Lands", imdb: "http://www.imdb.com/title/tt2069318/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_Night_Lands", season_id: 2 )
Episode.create!( episodeNumber: 3,name: "What is Dead May Never Die",wikia: "http://gameofthrones.wikia.com/wiki/What_is_Dead_May_Never_Die", imdb: "http://www.imdb.com/title/tt2070135/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/What_Is_Dead_May_Never_Die", season_id: 2 )
Episode.create!( episodeNumber: 4,name: "Garden of Bones",wikia: "http://gameofthrones.wikia.com/wiki/Garden_of_Bones", imdb: "http://www.imdb.com/title/tt2069319/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Garden_of_Bones", season_id: 2 )
Episode.create!( episodeNumber: 5,name: "The Ghost of Harrenhal",wikia: "http://gameofthrones.wikia.com/wiki/The_Ghost_of_Harrenhal", imdb: "http://www.imdb.com/title/tt2074658/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_Ghost_of_Harrenhal", season_id: 2 )
Episode.create!( episodeNumber: 6,name: "The Old Gods and the New",wikia: "http://gameofthrones.wikia.com/wiki/The_Old_Gods_and_the_New", imdb: "http://www.imdb.com/title/tt2085238/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_Old_Gods_and_the_New", season_id: 2 )
Episode.create!( episodeNumber: 7,name: "A Man Without Honor",wikia: "http://gameofthrones.wikia.com/wiki/A_Man_Without_Honor", imdb: "http://www.imdb.com/title/tt2085239/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/A_Man_Without_Honor", season_id: 2 )
Episode.create!( episodeNumber: 8,name: "The Prince of Winterfell",wikia: "http://gameofthrones.wikia.com/wiki/The_Prince_of_Winterfell", imdb: "http://www.imdb.com/title/tt2085240/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_Prince_of_Winterfell", season_id: 2 )
Episode.create!( episodeNumber: 9,name: "Blackwater",wikia: "http://gameofthrones.wikia.com/wiki/Blackwater", imdb: "http://www.imdb.com/title/tt2084342/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Blackwater_(Game_of_Thrones)", season_id: 2 )
Episode.create!( episodeNumber: 10,name: "Valar Morghulis",wikia: "http://gameofthrones.wikia.com/wiki/Valar_Morghulis", imdb: "http://www.imdb.com/title/tt2112510/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Valar_Morghulis", season_id: 2 )
Episode.create!( episodeNumber: 1,name: "Valar Dohaeris",wikia: "http://gameofthrones.wikia.com/wiki/Valar_Dohaeris", imdb: "http://www.imdb.com/title/tt2178782/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Valar_Dohaeris", season_id: 3 )
Episode.create!( episodeNumber: 2,name: "Dark Wings, Dark Words",wikia: "http://gameofthrones.wikia.com/wiki/Dark_Wings,_Dark_Words", imdb: "http://www.imdb.com/title/tt2178772/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Dark_Wings,_Dark_Words", season_id: 3 )
Episode.create!( episodeNumber: 3,name: "Walk of Punishment",wikia: "http://gameofthrones.wikia.com/wiki/Walk_of_Punishment", imdb: "http://www.imdb.com/title/tt2178802/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Walk_of_Punishment", season_id: 3 )
Episode.create!( episodeNumber: 4,name: "And Now His Watch is Ended",wikia: "http://gameofthrones.wikia.com/wiki/And_Now_His_Watch_is_Ended", imdb: "http://www.imdb.com/title/tt2178798/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/And_Now_His_Watch_Is_Ended", season_id: 3 )
Episode.create!( episodeNumber: 5,name: "Kissed by Fire",wikia: "http://gameofthrones.wikia.com/wiki/Kissed_by_Fire", imdb: "http://www.imdb.com/title/tt2178788/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Kissed_by_Fire", season_id: 3 )
Episode.create!( episodeNumber: 6,name: "The Climb",wikia: "http://gameofthrones.wikia.com/wiki/The_Climb", imdb: "http://www.imdb.com/title/tt2178812/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_Climb_(Game_of_Thrones)", season_id: 3 )
Episode.create!( episodeNumber: 7,name: "The Bear and the Maiden Fair",wikia: "http://gameofthrones.wikia.com/wiki/The_Bear_and_the_Maiden_Fair_(episode)", imdb: "http://www.imdb.com/title/tt2178814/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_Bear_and_the_Maiden_Fair", season_id: 3 )
Episode.create!( episodeNumber: 8,name: "Second Sons",wikia: "http://gameofthrones.wikia.com/wiki/Second_Sons_(episode)", imdb: "http://www.imdb.com/title/tt2178806/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Second_Sons", season_id: 3 )
Episode.create!( episodeNumber: 9,name: "The Rains of Castamere",wikia: "http://gameofthrones.wikia.com/wiki/The_Rains_of_Castamere_(episode)", imdb: "http://www.imdb.com/title/tt2178784/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_Rains_of_Castamere", season_id: 3 )
Episode.create!( episodeNumber: 10,name: "Mhysa",wikia: "http://gameofthrones.wikia.com/wiki/Mhysa", imdb: "http://www.imdb.com/title/tt2178796/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Mhysa", season_id: 3 )
Episode.create!( episodeNumber: 1,name: "Two Swords",wikia: "http://gameofthrones.wikia.com/wiki/Two_Swords", imdb: "http://www.imdb.com/title/tt2816136/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Two_Swords_(Game_of_Thrones)", season_id: 4 )
Episode.create!( episodeNumber: 2,name: "The Lion and the Rose",wikia: "http://gameofthrones.wikia.com/wiki/The_Lion_and_the_Rose", imdb: "http://www.imdb.com/title/tt2832378/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_Lion_and_the_Rose", season_id: 4 )
Episode.create!( episodeNumber: 3,name: "Breaker of Chains",wikia: "http://gameofthrones.wikia.com/wiki/Breaker_of_Chains", imdb: "http://www.imdb.com/title/tt2972426/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Breaker_of_Chains", season_id: 4 )
Episode.create!( episodeNumber: 4,name: "Oathkeeper",wikia: "http://gameofthrones.wikia.com/wiki/Oathkeeper", imdb: "http://www.imdb.com/title/tt2972428/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Oathkeeper", season_id: 4 )
Episode.create!( episodeNumber: 5,name: "First of His Name",wikia: "http://gameofthrones.wikia.com/wiki/First_of_His_Name", imdb: "http://www.imdb.com/title/tt3060856/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/First_of_His_Name", season_id: 4 )
Episode.create!( episodeNumber: 6,name: "The Laws of Gods and Men",wikia: "http://gameofthrones.wikia.com/wiki/The_Laws_of_Gods_and_Men", imdb: "http://www.imdb.com/title/tt3060910/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_Laws_of_Gods_and_Men", season_id: 4 )
Episode.create!( episodeNumber: 7,name: "Mockingbird",wikia: "http://gameofthrones.wikia.com/wiki/Mockingbird", imdb: "http://www.imdb.com/title/tt3060876/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Mockingbird_(Game_of_Thrones)", season_id: 4 )
Episode.create!( episodeNumber: 8,name: "The Mountain and the Viper",wikia: "http://gameofthrones.wikia.com/wiki/The_Mountain_and_the_Viper", imdb: "http://www.imdb.com/title/tt3060782/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_Mountain_and_the_Viper", season_id: 4 )
Episode.create!( episodeNumber: 9,name: "The Watchers on the Wall",wikia: "http://gameofthrones.wikia.com/wiki/The_Watchers_on_the_Wall", imdb: "http://www.imdb.com/title/tt3060858/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_Watchers_on_the_Wall", season_id: 4 )
Episode.create!( episodeNumber: 10,name: "The Children",wikia: "http://gameofthrones.wikia.com/wiki/The_Children", imdb: "http://www.imdb.com/title/tt3060860/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_Children_(Game_of_Thrones)", season_id: 4 )
Episode.create!( episodeNumber: 1,name: "The Wars to Come",wikia: "http://gameofthrones.wikia.com/wiki/The_Wars_to_Come", imdb: "http://www.imdb.com/title/tt3658012/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_Wars_to_Come", season_id: 5 )
Episode.create!( episodeNumber: 2,name: "The House of Black and White",wikia: "http://gameofthrones.wikia.com/wiki/The_House_of_Black_and_White", imdb: "http://www.imdb.com/title/tt3846626/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_House_of_Black_and_White", season_id: 5 )
Episode.create!( episodeNumber: 3,name: "High Sparrow",wikia: "http://gameofthrones.wikia.com/wiki/High_Sparrow_(episode)", imdb: "http://www.imdb.com/title/tt3866836/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/High_Sparrow", season_id: 5 )
Episode.create!( episodeNumber: 4,name: "Sons of the Harpy",wikia: "http://gameofthrones.wikia.com/wiki/Sons_of_the_Harpy_(episode)", imdb: "http://www.imdb.com/title/tt3866838/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Sons_of_the_Harpy", season_id: 5 )
Episode.create!( episodeNumber: 5,name: "Kill the Boy",wikia: "http://gameofthrones.wikia.com/wiki/Kill_the_Boy", imdb: "http://www.imdb.com/title/tt3866840/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Kill_the_Boy", season_id: 5 )
Episode.create!( episodeNumber: 6,name: "Unbowed, Unbent, Unbroken",wikia: "http://gameofthrones.wikia.com/wiki/Unbowed,_Unbent,_Unbroken", imdb: "http://www.imdb.com/title/tt3866842/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Unbowed,_Unbent,_Unbroken", season_id: 5 )
Episode.create!( episodeNumber: 7,name: "The Gift",wikia: "http://gameofthrones.wikia.com/wiki/The_Gift_(episode)", imdb: "http://www.imdb.com/title/tt3866846/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_Gift_(Game_of_Thrones)", season_id: 5 )
Episode.create!( episodeNumber: 8,name: "Hardhome",wikia: "http://gameofthrones.wikia.com/wiki/Hardhome_(episode)", imdb: "http://www.imdb.com/title/tt3866850/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Hardhome", season_id: 5 )
Episode.create!( episodeNumber: 9,name: "The Dance of Dragons",wikia: "http://gameofthrones.wikia.com/wiki/The_Dance_of_Dragons", imdb: "http://www.imdb.com/title/tt3866826/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/The_Dance_of_Dragons", season_id: 5 )
Episode.create!( episodeNumber: 10,name: "Mother's Mercy",wikia: "http://gameofthrones.wikia.com/wiki/Mother%27s_Mercy", imdb: "http://www.imdb.com/title/tt3866862/?ref_=tt_ep_nx", wiki: "https://en.wikipedia.org/wiki/Mother%27s_Mercy", season_id: 5 )

Episode.create!( episodeNumber: 1,name: "The Red Woman", season_id: 6 )
Episode.create!( episodeNumber: 2,name: "Home", season_id: 6 )
Episode.create!( episodeNumber: 3,name: "Oathbreaker", season_id: 6 )
Episode.create!( episodeNumber: 4,name: "Book of the Stranger", season_id: 6 )
Episode.create!( episodeNumber: 5,name: "The Door", season_id: 6 )
Episode.create!( episodeNumber: 6,name: "Blood of My Blood", season_id: 6 )
Episode.create!( episodeNumber: 7,name: "The Broken Man", season_id: 6 )
Episode.create!( episodeNumber: 8,name: "No One", season_id: 6 )
Episode.create!( episodeNumber: 9,name: "Battle of the Bastards", season_id: 6 )
Episode.create!( episodeNumber: 10,name: "The Winds of Winter", season_id: 6 )


Death.create!(name: "Waymar Royce", time: "5:52", link: "http://gameofthrones.wikia.com/wiki/Waymar_Royce", killedBy: "Killed by White Walker",importance: 1,episode_id: 1 )
Death.create!(name: "Gared", time: "6:58", link: "http://gameofthrones.wikia.com/wiki/Gared", killedBy: "Killed by White Walker",importance: 1,episode_id: 1 )
Death.create!(name: "Will", time: "13:44", link: "http://gameofthrones.wikia.com/wiki/Will", killedBy: "Executed by Ned Stark",importance: 1,episode_id: 1 )
Death.create!(name: "Jon Arryn", time: "18:34", link: "http://gameofthrones.wikia.com/wiki/Jon_Arryn", killedBy: "Poisoned by Lysa",house: "Arryn",importance: 1,episode_id: 1 )
Death.create!(name: "Assassin", time: "31:27", link: "http://gameofthrones.wikia.com/wiki/Catspaw_assassin", killedBy: "Killed by Bran's Wolf",importance: 1,episode_id: 2 )
Death.create!(name: "Mycah", time: "4:37", link: "http://gameofthrones.wikia.com/wiki/Mycah", killedBy: "Killed by the Hound",importance: 1,episode_id: 2 )
Death.create!(name: "Ser Hugh", time: "47:41", link: "http://gameofthrones.wikia.com/wiki/Hugh", killedBy: "Killed by the Mountain",importance: 1,episode_id: 4 )
Death.create!(name: "Kurleket", time: "11:56", link: "http://gameofthrones.wikia.com/wiki/Kurleket", killedBy: "Killed by hill tribesmen",importance: 1,episode_id: 5 )
Death.create!(name: "Willis Wode", time: "12:31", link: "http://gameofthrones.wikia.com/wiki/Willis_Wode", killedBy: "Killed by hill tribesmen",importance: 1,episode_id: 5 )
Death.create!(name: "Wyl", time: "51:14", link: "http://gameofthrones.wikia.com/wiki/Wyl_(House_Stark)", killedBy: "Killed by Lannister guardsmen",importance: 1,episode_id: 5 )
Death.create!(name: "Heward", time: "51:14", link: "http://gameofthrones.wikia.com/wiki/Heward", killedBy: "Killed by Lannister guardsmen",importance: 1,episode_id: 5 )
Death.create!(name: "Jory Cassel", time: "51:30", link: "http://gameofthrones.wikia.com/wiki/Jory_Cassel", killedBy: "Killed by Jamie Lannister",importance: 2,episode_id: 5 )
Death.create!(name: "Wallen", time: "11:23", link: "http://gameofthrones.wikia.com/wiki/Wallen", killedBy: "Killed by Rob Stark",importance: 1,episode_id: 6 )
Death.create!(name: "Stiv", time: "12:05", link: "http://gameofthrones.wikia.com/wiki/Stiv", killedBy: "Kill by Theon Greyjoy",importance: 1,episode_id: 6 )
Death.create!(name: "Vardis Egen", time: "38:19", link: "http://gameofthrones.wikia.com/wiki/Vardis_Egen", killedBy: "Killed by Bronn",importance: 1,episode_id: 6 )
Death.create!(name: "Viserys Targaryen ", time: "51:04", link: "http://gameofthrones.wikia.com/wiki/Viserys_Targaryen", killedBy: "Killed by Khal Drogo",house: "Targaryen",importance: 3,episode_id: 6 )
Death.create!(name: "Wine seller", time: "51:53", link: "http://gameofthrones.wikia.com/wiki/Wineseller", killedBy: "Dragged behind a Horse",importance: 1,episode_id: 7 )
Death.create!(name: "Robert Baratheon", time: "52:09", link: "http://gameofthrones.wikia.com/wiki/Robert_Baratheon", killedBy: "Killed by a boar",house: "Baratheon",importance: 3,episode_id: 7 )
Death.create!(name: "Vayon Poole", time: "2:25", link: "http://gameofthrones.wikia.com/wiki/Vayon_Poole", killedBy: "Killed by House Lannister men",importance: 1,episode_id: 8 )
Death.create!(name: "Mordane", time: "3:12", link: "http://gameofthrones.wikia.com/wiki/Mordane", killedBy: "Killed by House Lannister men",importance: 1,episode_id: 8 )
Death.create!(name: "Syrio Forel", time: "5:46", link: "http://gameofthrones.wikia.com/wiki/Syrio_Forel", killedBy: "Killed by House Lannister men",importance: 1,episode_id: 8 )
Death.create!(name: "Stableboy", time: "7:02", link: "http://gameofthrones.wikia.com/wiki/Stableboy", killedBy: "Killed by Arya",importance: 1,episode_id: 8 )
Death.create!(name: "Mago", time: "30:52", link: "http://gameofthrones.wikia.com/wiki/Mago", killedBy: "Killed by Khal Drogo",importance: 1,episode_id: 8 )
Death.create!(name: "Othor", time: "25:58", link: "http://gameofthrones.wikia.com/wiki/Othor", killedBy: "Burned by Jon Snow",importance: 1,episode_id: 8 )
Death.create!(name: "Qotho", time: "34:02", link: "http://gameofthrones.wikia.com/wiki/Qotho", killedBy: "Killed by Jorah Mormont",importance: 2,episode_id: 9 )
Death.create!(name: "Eddard Stark", time: "54:56", link: "http://gameofthrones.wikia.com/wiki/Eddard_Stark", killedBy: "Executed by Ilyn Payne",house: "Stark",importance: 3,episode_id: 9 )
Death.create!(name: "Khal Drogo", time: "33:39", link: "http://gameofthrones.wikia.com/wiki/Khal_Drogo", killedBy: "Smothered by Daenerys",importance: 3,episode_id: 10 )
Death.create!(name: "Mirri Maz Duur", time: "48:12", link: "http://gameofthrones.wikia.com/wiki/Mirri_Maz_Duur", killedBy: "Burned alive by by Daenerys",importance: 1,episode_id: 10 )
Death.create!(name: "Maester Cressen", time: "30:49", link: "http://gameofthrones.wikia.com/wiki/Cressen", killedBy: "Suicide by poison",importance: 1,episode_id: 11 )
Death.create!(name: "Barra", time: "49:21", link: "http://gameofthrones.wikia.com/wiki/Barra", killedBy: "killed by Janos Slynt",importance: 1,episode_id: 11 )
Death.create!(name: "Rakharo", time: "15:52", link: "http://gameofthrones.wikia.com/wiki/Rakharo", killedBy: "Killed by Dothrakis",importance: 2,episode_id: 12 )
Death.create!(name: "Yoren", time: "48:22", link: "http://gameofthrones.wikia.com/wiki/Yoren", killedBy: "killed by Amory Lorch",importance: 2,episode_id: 13 )
Death.create!(name: "Lommy", time: "50:13", link: "http://gameofthrones.wikia.com/wiki/Lommy", killedBy: "Killed by Polliver",importance: 2,episode_id: 13 )
Death.create!(name: "Rennick", time: "3:39", link: "http://gameofthrones.wikia.com/wiki/Rennick", killedBy: "killed by Robb Stark's wolf",importance: 1,episode_id: 14 )
Death.create!(name: "Lannister guardsmen", time: "3:39", link: "http://gameofthrones.wikia.com/wiki/Lannister_guardsman_(Garden_of_Bones)", killedBy: "killed by Robb Stark's wolf",importance: 1,episode_id: 14 )
Death.create!(name: "Tortured Prisoner", time: "28:13", link: "http://gameofthrones.wikia.com/wiki/Tortured_prisoner", killedBy: "Tortured to death ",importance: 1,episode_id: 14 )
Death.create!(name: "Renly Baratheon", time: "3:38", link: "http://gameofthrones.wikia.com/wiki/Renly_Baratheon", killedBy: "Killed by shadow creature",house: "Baratheon",importance: 3,episode_id: 15 )
Death.create!(name: "Emmon Cuy", time: "4:04", link: "http://gameofthrones.wikia.com/wiki/Emmon_Cuy", killedBy: "killed by Brienne of Tarth",importance: 1,episode_id: 15 )
Death.create!(name: "Robar Royce", time: "4:12", link: "http://gameofthrones.wikia.com/wiki/Robar_Royce", killedBy: "killed by Brienne of Tarth",importance: 1,episode_id: 15 )
Death.create!(name: "The Tickler", time: "52:10", link: "http://gameofthrones.wikia.com/wiki/The_Tickler", killedBy: "Killed by Jaqen H'ghar",importance: 1,episode_id: 15 )
Death.create!(name: "Rodrik Cassel", time: "9:35", link: "http://gameofthrones.wikia.com/wiki/Rodrik_Cassel", killedBy: "Killed by Theon Greyjoy ",importance: 2,episode_id: 16 )
Death.create!(name: "The High Septon", time: "26:25", link: "http://gameofthrones.wikia.com/wiki/High_Septon_(Before_the_riot_of_King%27s_Landing)", killedBy: "Killed by rioters",importance: 1,episode_id: 16 )
Death.create!(name: "Armory Lorch", time: "38:41", link: "http://gameofthrones.wikia.com/wiki/Amory_Lorch", killedBy: "Killed by Jagen H'ghar",importance: 1,episode_id: 16 )
Death.create!(name: "Drennan ", time: "50:19", link: "http://gameofthrones.wikia.com/wiki/Drennan", killedBy: "Killed by Osha",importance: 1,episode_id: 16 )
Death.create!(name: "Irri", time: "52:00", link: "http://gameofthrones.wikia.com/wiki/Irri", killedBy: "Killed by Xaro Xhoan Daxos",importance: 2,episode_id: 16 )
Death.create!(name: "Alton Lannister", time: "38:38", link: "http://gameofthrones.wikia.com/wiki/Alton_Lannister", killedBy: "Killed by Jamie Lannister",house: "Lannister",importance: 1,episode_id: 17 )
Death.create!(name: "Torrhen Karstark", time: "39:07", link: "http://gameofthrones.wikia.com/wiki/Torrhen_Karstark", killedBy: "Killed by Jamie Lannister",importance: 1,episode_id: 17 )
Death.create!(name: "Eleven of the Thirteen", time: "42:41", link: "http://gameofthrones.wikia.com/wiki/The_Thirteen", killedBy: "Killed by Pyat Pree",importance: 1,episode_id: 17 )
Death.create!(name: "Billy", time: "53:27", link: "http://gameofthrones.wikia.com/wiki/Billy", killedBy: "Killed by Theon Greyjoy",importance: 1,episode_id: 17 )
Death.create!(name: "Jack", time: "53:27", link: "http://gameofthrones.wikia.com/wiki/Jack", killedBy: "Killed by Theon Greyjoy",importance: 1,episode_id: 17 )
Death.create!(name: "Stonesnake", time: "7:24", link: "http://gameofthrones.wikia.com/wiki/Stonesnake", killedBy: "killed by wildlings",importance: 1,episode_id: 18 )
Death.create!(name: "Harker", time: "7:24", link: "http://gameofthrones.wikia.com/wiki/Harker", killedBy: "killed by wildlings",importance: 1,episode_id: 18 )
Death.create!(name: "Borba ", time: "7:24", link: "http://gameofthrones.wikia.com/wiki/Borba", killedBy: "killed by wildlings",importance: 1,episode_id: 18 )
Death.create!(name: "Matthos Seaworth", time: "25:09", link: "http://gameofthrones.wikia.com/wiki/Matthos_Seaworth", killedBy: "killed by Wildfire explosion",importance: 2,episode_id: 19 )
Death.create!(name: "Mandon Moore", time: "49:47", link: "http://gameofthrones.wikia.com/wiki/Mandon_Moore", killedBy: "killed by Podrik",importance: 1,episode_id: 19 )
Death.create!(name: "Tom", time: "15:51", link: "http://gameofthrones.wikia.com/wiki/Tom", killedBy: "killed by Brienne of Tarth",importance: 1,episode_id: 20 )
Death.create!(name: "Maester Luwin", time: "28:31", link: "http://gameofthrones.wikia.com/wiki/Luwin", killedBy: "Killed by Dagmer",importance: 2,episode_id: 20 )
Death.create!(name: "Pyat Pree", time: "51:08", link: "http://gameofthrones.wikia.com/wiki/Pyat_Pree", killedBy: "Killed by Daenerys' dragons",importance: 2,episode_id: 20 )
Death.create!(name: "Qhorin", time: "53:26", link: "http://gameofthrones.wikia.com/wiki/Qhorin_Halfhand", killedBy: "Killed by Jon Snow",importance: 2,episode_id: 20 )
Death.create!(name: "Doreah", time: "56:46", link: "http://gameofthrones.wikia.com/wiki/Doreah", killedBy: "Locked in Xaro Xhoan Daxos' vault",importance: 2,episode_id: 20 )
Death.create!(name: "Xaro Xhoan Daxos", time: "56:46", link: "http://gameofthrones.wikia.com/wiki/Xaro_Xhoan_Daxos", killedBy: "Locked in his vault",importance: 2,episode_id: 20 )
Death.create!(name: "Hoster Tully", time: "5:31", link: "http://gameofthrones.wikia.com/wiki/Hoster_Tully", killedBy: "Old age",house: "Tully",importance: 1,episode_id: 22 )
Death.create!(name: "Master Torturer", time: "45:14", link: "http://gameofthrones.wikia.com/wiki/Master_Torturer", killedBy: "Killed by Ramsay Snow",importance: 1,episode_id: 23 )
Death.create!(name: "Bannen", time: "34:51", link: "http://gameofthrones.wikia.com/wiki/Bannen", killedBy: "Died of a broken foot and being starved",importance: 1,episode_id: 24 )
Death.create!(name: "Caster", time: "38:39", link: "http://gameofthrones.wikia.com/wiki/Craster", killedBy: "killed by Karl Tanner",importance: 2,episode_id: 24 )
Death.create!(name: "Jeor Mormont", time: "39:03", link: "http://gameofthrones.wikia.com/wiki/Jeor_Mormont", killedBy: "killed by Rast",importance: 2,episode_id: 24 )
Death.create!(name: "Kraznys mo Nakloz", time: "49:00", link: "http://gameofthrones.wikia.com/wiki/Kraznys_mo_Nakloz", killedBy: "Killed by dragon",importance: 1,episode_id: 24 )
Death.create!(name: "Willen Lannister", time: "20:55", link: "http://gameofthrones.wikia.com/wiki/Willem_Lannister", killedBy: "killed by Richard Karstark",house: "Lannister",importance: 1,episode_id: 25 )
Death.create!(name: "Martyn Lannister", time: "20:58", link: "http://gameofthrones.wikia.com/wiki/Martyn_Lannister", killedBy: "killed by Richard Karstark",house: "Lannister",importance: 1,episode_id: 25 )
Death.create!(name: "Richard Karstark", time: "25:09", link: "http://gameofthrones.wikia.com/wiki/Rickard_Karstark", killedBy: "Executed by Robb Stark",importance: 2,episode_id: 25 )
Death.create!(name: "Ros", time: "48:40", link: "http://gameofthrones.wikia.com/wiki/Ros", killedBy: "killed by Joffrey",importance: 2,episode_id: 26 )
Death.create!(name: "Mero", time: "45:11", link: "http://gameofthrones.wikia.com/wiki/Mero", killedBy: "Killed by Daario Naharis",importance: 1,episode_id: 28 )
Death.create!(name: "Prendahl na Ghezn", time: "45:11", link: "http://gameofthrones.wikia.com/wiki/Prendahl_na_Ghezn", killedBy: "Killed by Daario Naharis",importance: 1,episode_id: 28 )
Death.create!(name: "White Walker", time: "54:25", link: "http://gameofthrones.wikia.com/wiki/White_Walker_(Valar_Morghulis)", killedBy: "White Walker",importance: 1,episode_id: 28 )
Death.create!(name: "Old Man", time: "25:04", link: "http://gameofthrones.wikia.com/wiki/Old_man", killedBy: "Killed by Ygritte",importance: 1,episode_id: 29 )
Death.create!(name: "Orell", time: "26:20", link: "http://gameofthrones.wikia.com/wiki/Orell", killedBy: "Killed by Jon Snow",importance: 2,episode_id: 29 )
Death.create!(name: "Talisa Stark", time: "44:15", link: "http://gameofthrones.wikia.com/wiki/Talisa_Stark", killedBy: "killed by Lorthar Frey",house: "Stark",importance: 3,episode_id: 29 )
Death.create!(name: "Robb Stark", time: "48:37", link: "http://gameofthrones.wikia.com/wiki/Robb_Stark", killedBy: "Killed by Roose Bolton",house: "Stark",importance: 3,episode_id: 29 )
Death.create!(name: "Joyeuse Erenford", time: "48:57", link: "http://gameofthrones.wikia.com/wiki/Joyeuse_Erenford", killedBy: "killed by Catelyn Stark",importance: 1,episode_id: 29 )
Death.create!(name: "Catelyn Stark", time: "49:05", link: "http://gameofthrones.wikia.com/wiki/Catelyn_Stark", killedBy: "Killed by Walder Rivers",house: "Stark",importance: 3,episode_id: 29 )
Death.create!(name: "Frey Soldier", time: "40:00", link: "http://gameofthrones.wikia.com/wiki/Frey_soldier_1", killedBy: "Killed by Arya Stark",importance: 1,episode_id: 30 )
Death.create!(name: "lowell", time: "55:00", link: "http://gameofthrones.wikia.com/wiki/Lowell", killedBy: "Killed by the Hound",importance: 1,episode_id: 31 )
Death.create!(name: "Polliver", time: "55:30", link: "http://gameofthrones.wikia.com/wiki/Polliver", killedBy: "Killed by Arya Stark",importance: 1,episode_id: 31 )
Death.create!(name: "Tansy", time: "3:59", link: "http://gameofthrones.wikia.com/wiki/Tansy", killedBy: "Killed by Ramsey's Dogs",importance: 1,episode_id: 32 )
Death.create!(name: "Axell Florent", time: "20:10", link: "http://gameofthrones.wikia.com/wiki/Axell_Florent", killedBy: "Burned alive by Melisandre",importance: 1,episode_id: 32 )
Death.create!(name: "Joffrey Baratheon", time: "47:46", link: "http://gameofthrones.wikia.com/wiki/Joffrey_Baratheon", killedBy: "Poisoned by Olenna Tyrell",house: "Baratheon",importance: 3,episode_id: 32 )
Death.create!(name: "Dontos Hollar", time: "4:46", link: "http://gameofthrones.wikia.com/wiki/Dontos_Hollard", killedBy: "killed by Petyr Baelish's men",importance: 2,episode_id: 33 )
Death.create!(name: "Guymon", time: "43:40", link: "http://gameofthrones.wikia.com/wiki/Guymon", killedBy: "Killed by Ygritte",importance: 1,episode_id: 33 ) 
Death.create!(name: "Olly's Mother", time: "43:50", link: "http://gameofthrones.wikia.com/wiki/Olly%27s_mother", killedBy: "Killed by Styr",importance: 1,episode_id: 33 )
Death.create!(name: "Oznak zo Pahl", time: "52:30", link: "http://gameofthrones.wikia.com/wiki/Oznak_zo_Pahl", killedBy: "Killed by Daario Naharis",importance: 1,episode_id: 33 )
Death.create!(name: "Great Master", time: "7:45", link: "http://gameofthrones.wikia.com/wiki/Great_Master_1", killedBy: "killed slaves in uprising",importance: 1,episode_id: 34 )
Death.create!(name: "Locke", time: "44:46", link: "http://gameofthrones.wikia.com/wiki/Locke", killedBy: " Killed Bran Stark while warging into Hodor",importance: 2,episode_id: 35 )
Death.create!(name: "Karl Tanner", time: "47:51", link: "http://gameofthrones.wikia.com/wiki/Karl_Tanner", killedBy: "Killed by Jon Snow",importance: 2,episode_id: 35 )
Death.create!(name: "Rast", time: "49:47", link: "http://gameofthrones.wikia.com/wiki/Rast", killedBy: "Killed by Jon Snow's wolf",importance: 2,episode_id: 35 )
Death.create!(name: "Dying Man", time: "8:57", link: "http://gameofthrones.wikia.com/wiki/Dying_man", killedBy: "Mercy killed by the Hound",importance: 1,episode_id: 37 )
Death.create!(name: "Biter", time: "9:39", link: "http://gameofthrones.wikia.com/wiki/Biter", killedBy: "Killed by the Hound",importance: 1,episode_id: 37 )
Death.create!(name: "Rorge", time: "10:29", link: "http://gameofthrones.wikia.com/wiki/Rorge", killedBy: "Killed by Arya Stark",importance: 1,episode_id: 37 )
Death.create!(name: "Lysa Arryn", time: "49:19", link: "http://gameofthrones.wikia.com/wiki/Lysa_Arryn", killedBy: "Pushed through the moon door by Littlefinger",house: "Arryn",importance: 2,episode_id: 37 )
Death.create!(name: "Mole's Town whore", time: "5:08", link: "http://gameofthrones.wikia.com/wiki/Mole%27s_Town_whore", killedBy: "Killed by Ygritte",importance: 1,episode_id: 38 )
Death.create!(name: "Ralf Kenning", time: "16:41", link: "http://gameofthrones.wikia.com/wiki/Ralf_Kenning", killedBy: "killed by Adrack Humble",importance: 1,episode_id: 38 )
Death.create!(name: "Adrack Humble", time: "17:07", link: "http://gameofthrones.wikia.com/wiki/Adrack_Humble", killedBy: "Killed by Ramsay Snow's men",importance: 1,episode_id: 38 )
Death.create!(name: "Oberyn Martell", time: "50:05", link: "http://gameofthrones.wikia.com/wiki/Oberyn_Martell", killedBy: "Killed by the Mountain",house: "Martell",importance: 3,episode_id: 38 )
Death.create!(name: "Pypar", time: "29:44", link: "http://gameofthrones.wikia.com/wiki/Oberyn_Martell", killedBy: "Killed by Ygritte",importance: 2,episode_id: 39 )
Death.create!(name: "Thenn warg", time: "34:00", link: "http://gameofthrones.wikia.com/wiki/Thenn_Warg", killedBy: "Killed by Samwell Tarly",importance: 2,episode_id: 39 )
Death.create!(name: "Dongo", time: "35:44", link: "http://gameofthrones.wikia.com/wiki/Dongo", killedBy: "killed by Black Brothers",importance: 1,episode_id: 39 )
Death.create!(name: "Smitty", time: "36:02", link: "http://gameofthrones.wikia.com/wiki/Smitty", killedBy: "Fell of the wall",importance: 1,episode_id: 39 )
Death.create!(name: "Styr", time: "41:12", link: "http://gameofthrones.wikia.com/wiki/Styr", killedBy: "Killed by Jon Snow",importance: 2,episode_id: 39 )
Death.create!(name: "Ygritte", time: "41:39", link: "http://gameofthrones.wikia.com/wiki/Ygritte", killedBy: "Killed by Olly",importance: 3,episode_id: 39 )
Death.create!(name: "Mag Mar Tun Doh Weg", time: "47:02", link: "http://gameofthrones.wikia.com/wiki/Mag_Mar_Tun_Doh_Weg", killedBy: "killed by Grenn and 5 other black brothers",importance: 1,episode_id: 39 )
Death.create!(name: "Grenn", time: "47:02", link: "http://gameofthrones.wikia.com/wiki/Grenn", killedBy: "Killed by Mag Mar Tun Doh Weg",importance: 2,episode_id: 39 )
Death.create!(name: "Cooper", time: "47:02", link: "http://gameofthrones.wikia.com/wiki/Cooper", killedBy: "Killed by Mag Mar Tun Doh Weg",importance: 1,episode_id: 39 )
Death.create!(name: "Done Hill", time: "47:02", link: "http://gameofthrones.wikia.com/wiki/Donnel_Hill", killedBy: "Killed by Mag Mar Tun Doh Weg",importance: 1,episode_id: 39 )
Death.create!(name: "Zalla", time: "23:25", link: "http://gameofthrones.wikia.com/wiki/Zalla", killedBy: "killed by Dragon",importance: 1,episode_id: 40 )
Death.create!(name: "Jojen Reed", time: "35:56", link: "http://gameofthrones.wikia.com/wiki/Jojen_Reed", killedBy: "Killed by wight",importance: 2,episode_id: 40 )
# Death.create!(name: "Sandor Clegane", time: "51:04", link: "http://gameofthrones.wikia.com/wiki/Sandor_Clegane", killedBy: "Critically wounded by Brienne of Tarth",importance: 3,episode_id: 40 )
Death.create!(name: "Shae", time: "54:57", link: "http://gameofthrones.wikia.com/wiki/Shae", killedBy: "Killed by Tyrion Lannister",importance: 3,episode_id: 40 )
Death.create!(name: "Tywin Lannister", time: "58:45", link: "http://gameofthrones.wikia.com/wiki/Tywin_Lannister", killedBy: "killed by Tyrion Lannister",house: "Lannister",importance: 3,episode_id: 40 )
Death.create!(name: "White Rat", time: "15:20", link: "http://gameofthrones.wikia.com/wiki/White_Rat", killedBy: "Killed by a member of the Sons of the Harpy",importance: 1,episode_id: 41 )
Death.create!(name: "Mance Rayder", time: "49:18", link: "http://gameofthrones.wikia.com/wiki/Mance_Rayder", killedBy: "Mercy killed by Jon Snow",importance: 2,episode_id: 41 )
Death.create!(name: "Son of Harpy", time: "46:30", link: "http://gameofthrones.wikia.com/wiki/Mossador", killedBy: "Killed by Mossador",importance: 1,episode_id: 42 )
Death.create!(name: "Mossador", time: "50:24", link: "http://gameofthrones.wikia.com/wiki/Mossador", killedBy: "Executed by Daario Naharis",importance: 2,episode_id: 42 )
Death.create!(name: "Janos Slynt", time: "38:58", link: "http://gameofthrones.wikia.com/wiki/Janos_Slynt", killedBy: "Executed by Jon Snow",importance: 2,episode_id: 43 )
Death.create!(name: "Lead Dornish guard", time: "34:17", link: "http://gameofthrones.wikia.com/wiki/Lead_Dornish_Guard", killedBy: "Killed by Bronn",importance: 1,episode_id: 44 )
Death.create!(name: "Merchant captain", time: "38:42", link: "http://gameofthrones.wikia.com/wiki/Merchant_captain", killedBy: "Killed by Obara Sand",importance: 1,episode_id: 44 )
Death.create!(name: "Ser Barristan Selmy", time: "47:46", link: "http://gameofthrones.wikia.com/wiki/Barristan_Selmy", killedBy: "Killed by Sons of Harpy",importance: 2,episode_id: 44 )
Death.create!(name: "Great Master", time: "4:59", link: "http://gameofthrones.wikia.com/wiki/Eaton", killedBy: "Killed by dragon",importance: 1,episode_id: 45 )
Death.create!(name: "Ghita", time: "13:20", link: "http://gameofthrones.wikia.com/wiki/Ghita", killedBy: "Posioned with water from House of Black and White by Arya ",importance: 1,episode_id: 46 )
Death.create!(name: "Master Aemon", time: "9:45", link: "http://gameofthrones.wikia.com/wiki/Aemon", killedBy: "Died of natural causes",house: "Targaryen",importance: 2,episode_id: 47 )
Death.create!(name: "Old Woman", time: "13:42", link: "http://gameofthrones.wikia.com/wiki/Old_woman", killedBy: "Killed by Ramsay Bolton",importance: 1,episode_id: 47 )
Death.create!(name: "Lord of Bones", time: "32:50", link: "http://gameofthrones.wikia.com/wiki/Lord_of_Bones", killedBy: "killed by Tormund",importance: 2,episode_id: 48 )
Death.create!(name: "Loboda", time: "50:16", link: "http://gameofthrones.wikia.com/wiki/Loboda", killedBy: "Killed by White Walker",importance: 1,episode_id: 48 )
Death.create!(name: "White Walker", time: "51:00", link: "http://gameofthrones.wikia.com/wiki/White_Walker_(Hardhome)", killedBy: "killed by Jon Snow",importance: 1,episode_id: 48 )
Death.create!(name: "Karsi", time: "52:58", link: "http://gameofthrones.wikia.com/wiki/Karsi", killedBy: "Killed by a pack of child-wights",importance: 1,episode_id: 48 )
Death.create!(name: "Shrine Baratheon", time: "32:28", link: "http://gameofthrones.wikia.com/wiki/Shireen_Baratheon", killedBy: "Burned alive as a sacrifice by Melisandre",house: "Baratheon",importance: 2,episode_id: 49 )
Death.create!(name: "Hizdahr zo Loraq", time: "45:03", link: "http://gameofthrones.wikia.com/wiki/Hizdahr_zo_Loraq", killedBy: "Killed by son of Harpy",importance: 2,episode_id: 49 )
Death.create!(name: "Selyse Baratheon", time: "3:35", link: "http://gameofthrones.wikia.com/wiki/Selyse_Baratheon", killedBy: "Suicide by hanging",house: "Baratheon",importance: 2,episode_id: 50 )
Death.create!(name: "Stannis Baratheon", time: "15:23", link: "http://gameofthrones.wikia.com/wiki/Stannis_Baratheon", killedBy: "Killed by Brienne of Tarth",house: "Baratheon",importance: 3,episode_id: 50 )
Death.create!(name: "Myranda", time: "18:33", link: "http://gameofthrones.wikia.com/wiki/Myranda", killedBy: "Killed by Theon Greyjoy",importance: 2,episode_id: 50 )
Death.create!(name: "Meryn Trant", time: "21:10", link: "http://gameofthrones.wikia.com/wiki/Meryn_Trant", killedBy: "Killed by Arya Stark",importance: 2,episode_id: 50 )
Death.create!(name: "Myrcella Baratheon", time: "29:25", link: "http://gameofthrones.wikia.com/wiki/Myrcella_Baratheon", killedBy: "poisoned by Ellaria Sand ",house: "Baratheon",importance: 2,episode_id: 50 )
Death.create!(name: "Jon Snow", time: "56:20", link: "http://gameofthrones.wikia.com/wiki/Jon_Snow", killedBy: "Killed by Black brothers (Later Resurrected)",importance: 3,episode_id: 50 )
Death.create!(name: "Bolton officer", time: "15:47", killedBy: "Killed by Brienne of Tarth",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Bolton_officer",episode_id: 51 )
Death.create!(name: "Areo Hotah", time: "26:46", killedBy: "Stabbed in the back by Tyene Sand",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Areo_Hotah",episode_id: 51 )
Death.create!(name: "Doran Martell", time: "26:50", killedBy: "killed by Ellaria Sand",house: "Martell",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Doran_Martell",episode_id: 51 )
Death.create!(name: "Master Caleotte", time: "26:53", killedBy: "killed by Tyene Sand",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Caleotte",episode_id: 51 )
Death.create!(name: "Trystane Martell", time: "28:30", killedBy: "killed by Obara Sand",house: "Martell",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Trystane_Martell",episode_id: 51 )
Death.create!(name: "King's Landing boaster", time: "12:24", killedBy: "Killed by The Mountain",importance: 1, link: "http://gameofthrones.wikia.com/wiki/King%27s_Landing_boaster",episode_id: 52 )
Death.create!(name: "Roose Bolton", time: "31:04", killedBy: "Killed by Ramsay Bolton",house: "Bolton",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Roose_Bolton",episode_id: 52 )
Death.create!(name: "Walda Bolton", time: "35:17", killedBy: "Killed by Ramsay Bolton",house: "Bolton",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Walda_Bolton",episode_id: 52 )
Death.create!(name: "Newborn Bolton", time: "35:17", killedBy: "Killed by Ramsay Bolton",house: "Bolton",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Newborn_Bolton",episode_id: 52 )
Death.create!(name: "Balon Greyjoy", time: "42:21", killedBy: "Thrown from a bridge by Euron Greyjoy",house: "Greyjoy",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Balon_Greyjoy",episode_id: 52 )
Death.create!(name: "Gerold Hightower", time: "14:15", killedBy: "killed by Ned Stark",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Gerold_Hightower",episode_id: 53, status: "flashback")
Death.create!(name: "Arthur Dayne", time: "16:16", killedBy: "killed by Ned Stark",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Arthur_Dayne",episode_id: 53, status: "flashback")
Death.create!(name: "Jon Umber", time: "43:32", killedBy: "Died during the War of the Five Kings",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Jon_Umber",episode_id: 53 )
Death.create!(name: "Bowen Marsh", time: "49:17", killedBy: "Executed by Jon Snow",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Bowen_Marsh",episode_id: 53 )
Death.create!(name: "Othell Yarwyck", time: "49:17", killedBy: "Executed by Jon Snow",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Othell_Yarwyck",episode_id: 53 )
Death.create!(name: "Alliser Thorne", time: "49:17", killedBy: "Executed by Jon Snow",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Alliser_Thorne",episode_id: 53 )
Death.create!(name: "Olly", time: "49:17", killedBy: "Executed by Jon Snow",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Olly",episode_id: 53 )
Death.create!(name: "Iggo", time: "24:20", killedBy: "killed by Daario Naharis",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Iggo",episode_id: 54 )
Death.create!(name: "Akho", time: "24:39", killedBy: "killed by Daario Naharis",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Akho",episode_id: 54 )
Death.create!(name: "Osha", time: "46:18", killedBy: "killed by Ramsay Bolton",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Osha",episode_id: 54 )
Death.create!(name: "Moro and 9 other Khals", time: "54:27", killedBy: "Burned alive by Daenery",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Moro",episode_id: 54 )
Death.create!(name: "White Walker", time: "50:51", killedBy: "killed by Meera Reed",importance: 1, link: "http://gameofthrones.wikia.com/wiki/White_Walker_(The_Door)",episode_id: 55 )
Death.create!(name: "Three-eyed raven", time: "51:51", killedBy: "killed by the Night King",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Three-eyed_raven",episode_id: 55 )
Death.create!(name: "Leaf", time: "52:40", killedBy: "suicide by activating an explosive device taking out wights",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Leaf",episode_id: 55 )
Death.create!(name: "Hodor", time: "54:26", killedBy: "Torn apart by wights",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Hodor",episode_id: 55 )
Death.create!(name: "Aerys Targaryen", time: "2:49", killedBy: "Killed by Jaime Lannister",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Aerys_II_Targaryen",episode_id: 56, status: "flashback" )
Death.create!(name: "Maege Mormont", time: "23:14", killedBy: "Died during the War of the Five Kings",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Maege_Mormont",episode_id: 57 )
Death.create!(name: "Brother Ray & villagers", time: "48:13", killedBy: "killed by rogue members of the Brotherhood Without Banners",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Ray",episode_id: 57 )
Death.create!(name: "Steve", time: "8:24", killedBy: "killed by Sandor Clegane",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Steve",episode_id: 58 )
Death.create!(name: "Riddell", time: "8:26", killedBy: "killed by Sandor Clegane",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Riddell",episode_id: 58 )
Death.create!(name: "Morgan", time: "8:30", killedBy: "killed by Sandor Clegane",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Morgan_(season_6)",episode_id: 58 )
Death.create!(name: "Gatins", time: "8:33", killedBy: "killed by Sandor Clegane",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Gatins",episode_id: 58 )
Death.create!(name: "Faith Militant", time: "12:51", killedBy: "killed by The Mountain",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Faith_Militant",episode_id: 58 )
Death.create!(name: "Brynden Tully", time: "39:39", killedBy: "killed by Lannister soldier",house: "Tully",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Brynden_Tully",episode_id: 58 )
Death.create!(name: "Outlaw", time: "44:26", killedBy: "killed by Sandor Clegane",importance: 1, link: "http://gameofthrones.wikia.com/wiki/No_One",episode_id: 58 )
Death.create!(name: "Lem Lemoncloak", time: "44:31", killedBy: "killed by Sandor Clegane",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Lem_Lemoncloak",episode_id: 58 )
Death.create!(name: "Outlaw", time: "44:34", killedBy: "Hung by Brotherhood Without Banners",importance: 1, link: "http://gameofthrones.wikia.com/wiki/No_One",episode_id: 58 )
Death.create!(name: "Lady Crane", time: "47:45", killedBy: "Killed by the Waif ",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Lady_Crane",episode_id: 58 )
Death.create!(name: "The Waif ", time: "53:37", killedBy: "Kill by Arya Stark",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Waif",episode_id: 58 )
Death.create!(name: "Belicho Paenymion", time: "10:24", killedBy: "killed by Grey Worm",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Belicho_Paenymion",episode_id: 59 )
Death.create!(name: "Razdal mo Eraz", time: "10:24", killedBy: "killed by Grey Worm",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Razdal_mo_Eraz",episode_id: 59 )
Death.create!(name: "Rickon Stark", time: "35:26", killedBy: "Shot with an Arrow fired by Ramsay Bolton",house: "Stark",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Rickon_Stark",episode_id: 59 )
Death.create!(name: "Smalljon Umber", time: "47:36", killedBy: "killed by Tormund",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Smalljon_Umber",episode_id: 59 )
Death.create!(name: "Wun Weg Wun Dar Wun", time: "51:29", killedBy: "Shot with an Arrow fired by Ramsay Bolton",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Wun_Weg_Wun_Dar_Wun",episode_id: 59 )
Death.create!(name: "Ramsay Bolton", time: "51:13", killedBy: "Eaten alive by his own dogs",house: "Bolton",importance: 3, link: "http://gameofthrones.wikia.com/wiki/Ramsay_Bolton",episode_id: 59 )
Death.create!(name: "Grand Maester Pycelle", time: "13:07", killedBy: "killed by kids",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Pycelle",episode_id: 60 )
Death.create!(name: "Lancel Lannister", time: "17:17", killedBy: "killed by wildfire",house: "Lannister",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Lancel",episode_id: 60 )
Death.create!(name: "High Sparrow", time: "17:27", killedBy: "killed by wildfire",importance: 3, link: "http://gameofthrones.wikia.com/wiki/High_Sparrow",episode_id: 60 )
Death.create!(name: "Margaery Tyrell", time: "17:27", killedBy: "killed by wildfire",house: "Tyrell",importance: 3, link: "http://gameofthrones.wikia.com/wiki/Margaery_Tyrell",episode_id: 60 )
Death.create!(name: "Loras Tyrell", time: "17:27", killedBy: "killed by wildfire",house: "Tyrell",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Loras_Tyrell",episode_id: 60 )
Death.create!(name: "Mace Tyrell", time: "17:27", killedBy: "killed by wildfire",house: "Tyrell",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Mace_Tyrell",episode_id: 60 )
Death.create!(name: "Kevan Lannister", time: "17:27", killedBy: "killed by wild fire",house: "Lannister",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Kevan_Lannister",episode_id: 60 )
Death.create!(name: "Tommen Baratheon", time: "22:52", killedBy: "Suicide by juming out a window",house: "Baratheon",importance: 3, link: "http://gameofthrones.wikia.com/wiki/Tommen_Baratheon",episode_id: 60 )
Death.create!(name: "Walder Rivers", time: "48:30", killedBy: "killed by Arya Star",house: "Frey",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Walder_Rivers",episode_id: 60 )
Death.create!(name: "Lothar Frey", time: "48:30", killedBy: "killed by Arya Star",house: "Frey",importance: 1, link: "http://gameofthrones.wikia.com/wiki/Lothar_Frey",episode_id: 60 )
Death.create!(name: "Walder Frey", time: "49:03", killedBy: "killed by Arya Stark",house: "Frey",importance: 2, link: "http://gameofthrones.wikia.com/wiki/Walder_Frey",episode_id: 60 )

